version: '3.9'
services:
  web:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    restart: always
    build: .
    volumes:
      - ./src:/var/www/html
