version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        # php image url : https://hub.docker.com/repository/docker/patipark/php-fpm/general
        image: patipark/php-fpm:7.4-sqlsrv
        volumes:
            - ./src:/var/www/html

